### PR TITLE
Support both net7 and net8 at once

### PR DESCRIPTION
**Pull request by van800**
I had only net8 installed, so I had to make some changes to allow both net7 and net8

### CODE REVIEW

**Comment by MikeSchulze** [comment]
Thanks, for your help

**Comment by MikeSchulze** [comment]
hm, with .Net8 the test adapter breaks in VSCode
I'll have to take a look at why this no longer works with .NET8

**Comment by MikeSchulze** [comment]
i found the issue, the projects using Godot do not seperate the build output for .NET7 and .NET8, it saves just to `.godot`
I set the default for this project to .NET8 now and it works

**Comment by MikeSchulze** [comment]
Perhaps you have an idea where these warnings come from

`CSC : warning AD0001: Analyzer 'Godot.SourceGenerators.MustBeVariantAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/home/runner/work/gdUnit4Mono/gdUnit4Mono/test/gdUnit4Test.csproj::TargetFramework=net8.0]`

**Comment by van800** [comment]
It is from the Godot sources, however I don't know much 
https://github.com/godotengine/godot/issues?q=AD0001%3A+

**Pull request merged**
